# Generated by Django 5.0 on 2025-05-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComicBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('issue_number', models.PositiveIntegerField()),
                ('grade', models.PositiveIntegerField()),
                ('significance', models.TextField(blank=True, help_text='Significance of issue')),
                ('writer_name', models.CharField(max_length=150)),
                ('artist_name', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=75)),
            ],
        ),
    ]
