# Generated by Django 5.0 on 2025-05-07 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comicbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicbooks',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
