# Generated by Django 5.0 on 2025-05-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicbooks', '0003_comicbooks_cover_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicbooks',
            options={'ordering': ['title', 'issue_number']},
        ),
    ]
